PLUGIN=wavpack
DEFS= 
DEFFILE = wavpack/wavpack.def
SRCFILES_ARM  = wavpack/stdafx.c
SRCFILES_ARM += wavpack/wavpack.c
SRCFILES_ARM += wavpack/decoder/bits.c
SRCFILES_ARM += wavpack/decoder/float.c
SRCFILES_ARM += wavpack/decoder/metadata.c
SRCFILES_ARM += wavpack/decoder/unpack.c
SRCFILES_ARM += wavpack/decoder/words.c
SRCFILES_ARM += wavpack/decoder/wputils.c

SPECDIR = wavpack/decoder/
SPECFLAGS = -w

include plugin.inc
