PLUGIN=ac3
DEFS= -D LIBA52_FIXED
DEFFILE = ac3/ac3.def
SRCFILES_ARM  = ac3/stdafx.c 
SRCFILES_ARM += ac3/ac3.c 
SRCFILES_ARM += ac3/liba52/bit_allocate.c 
SRCFILES_ARM += ac3/liba52/bitstream2.c 
SRCFILES_ARM += ac3/liba52/crc.c 
SRCFILES_ARM += ac3/liba52/downmix.c 
SRCFILES_ARM += ac3/liba52/imdct.c 
SRCFILES_ARM += ac3/liba52/parse.c 

include plugin.inc
