PLUGIN=amr
DEFS= 
DEFFILE = amr/amr.def
SRCFILES_ARM  = amr/stdafx.c 
SRCFILES_ARM += amr/amrnb.c 
SRCFILES_ARM += amr/amrwb.c 
SRCFILES_ARM += amr/26104/interf_dec.c
SRCFILES_ARM += amr/26104/sp_dec.c
SRCFILES_ARM += amr/26204/dec_acelp.c
SRCFILES_ARM += amr/26204/dec_dtx.c
SRCFILES_ARM += amr/26204/dec_gain.c
SRCFILES_ARM += amr/26204/dec_if.c
SRCFILES_ARM += amr/26204/dec_lpc.c
SRCFILES_ARM += amr/26204/dec_main.c
SRCFILES_ARM += amr/26204/dec_rom.c
SRCFILES_ARM += amr/26204/dec_util.c
SRCFILES_ARM += amr/26204/if_rom.c

SPECDIR = amr/26104/
SPECFLAGS = -w

include plugin.inc
