PLUGIN=aac
DEFS = -DLC_ONLY_DECODER -DSTDC_HEADERS
DEFFILE = aac/aac.def
SRCFILES_ARM  = aac/stdafx.c 
SRCFILES_ARM += aac/faad.c 
SRCFILES_ARM += aac/libpaac/aac_imdct.c
SRCFILES_ARM += aac/faad2/libfaad/bits.c aac/faad2/libfaad/cfft.c
SRCFILES_ARM += aac/faad2/libfaad/common.c aac/faad2/libfaad/decoder.c
SRCFILES_ARM += aac/faad2/libfaad/drc.c aac/faad2/libfaad/drm_dec.c
SRCFILES_ARM += aac/faad2/libfaad/filtbank.c
SRCFILES_ARM += aac/faad2/libfaad/hcr.c aac/faad2/libfaad/huffman.c
SRCFILES_ARM += aac/faad2/libfaad/ic_predict.c aac/faad2/libfaad/is.c
SRCFILES_ARM += aac/faad2/libfaad/lt_predict.c aac/faad2/libfaad/mdct.c
SRCFILES_ARM += aac/faad2/libfaad/ms.c aac/faad2/libfaad/mp4.c
SRCFILES_ARM += aac/faad2/libfaad/output.c aac/faad2/libfaad/pns.c
SRCFILES_ARM += aac/faad2/libfaad/ps_dec.c aac/faad2/libfaad/ps_syntax.c
SRCFILES_ARM += aac/faad2/libfaad/rvlc.c aac/faad2/libfaad/pulse.c
SRCFILES_ARM += aac/faad2/libfaad/sbr_dct.c aac/faad2/libfaad/sbr_dec.c
SRCFILES_ARM += aac/faad2/libfaad/sbr_e_nf.c aac/faad2/libfaad/sbr_fbt.c
SRCFILES_ARM += aac/faad2/libfaad/sbr_hfadj.c aac/faad2/libfaad/sbr_hfgen.c
SRCFILES_ARM += aac/faad2/libfaad/sbr_huff.c aac/faad2/libfaad/sbr_qmf.c
SRCFILES_ARM += aac/faad2/libfaad/sbr_syntax.c aac/faad2/libfaad/sbr_tf_grid.c
SRCFILES_ARM += aac/faad2/libfaad/specrec.c aac/faad2/libfaad/ssr.c
SRCFILES_ARM += aac/faad2/libfaad/ssr_fb.c aac/faad2/libfaad/ssr_ipqf.c
SRCFILES_ARM += aac/faad2/libfaad/syntax.c aac/faad2/libfaad/tns.c

SPECDIR = aac/faad2/
SPECFLAGS = -w

include plugin.inc
