PLUGIN=matroska
DEFFILE = matroska/matroska.def
SRCFILES_ARM  = matroska/stdafx.c
SRCFILES_ARM += matroska/matroska.c 
SRCFILES_ARM += matroska/MatroskaParser/MatroskaParser.c 

SPECDIR = matroska/MatroskaParser/
SPECFLAGS = -Os

include plugin.inc
