PLUGIN=libmad
DEFS= -DFPM_ARM -DOPT_SPEED -DASO_INTERLEAVE1 
DEFFILE = libmad/libmad.def
SRCFILES_ARM  = libmad/stdafx.c 
SRCFILES_ARM += libmad/libmad.c
SRCFILES_ARM += libmad/libmad/bit.c 
SRCFILES_ARM += libmad/libmad/fixed.c
SRCFILES_ARM += libmad/libmad/frame.c 
SRCFILES_ARM += libmad/libmad/huffmanmad.c 
SRCFILES_ARM += libmad/libmad/layer12.c
SRCFILES_ARM += libmad/libmad/layer3.c 
SRCFILES_ARM += libmad/libmad/stream.c 
SRCFILES_ARM += libmad/libmad/synth.c 

include plugin.inc
